# Generated by Django 6.0.4 on 2026-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('racquet', models.CharField(blank=True, max_length=100)),
                ('play_style', models.CharField(choices=[('baseline', 'Baseline Player'), ('all_court', 'All-Court Player'), ('serve_volley', 'Serve and Volley'), ('counterpuncher', 'Counterpuncher'), ('aggressive', 'Aggressive Baseliner')], max_length=30)),
                ('strength', models.CharField(blank=True, max_length=200)),
                ('weakness', models.CharField(blank=True, max_length=200)),
                ('utr_rating', models.FloatField()),
            ],
        ),
    ]
